{"time":"2025-02-16T21:15:55.7738335+02:00","level":"INFO","msg":"stream: starting","core version":"0.19.4","symlink path":"C:\\dev\\EE569\\Assignment2-LLM\\wandb\\run-20250216_211555-5jw37dgl\\logs\\debug-core.log"}
{"time":"2025-02-16T21:15:55.8953629+02:00","level":"INFO","msg":"created new stream","id":"5jw37dgl"}
{"time":"2025-02-16T21:15:55.895875+02:00","level":"INFO","msg":"stream: started","id":"5jw37dgl"}
{"time":"2025-02-16T21:15:55.896751+02:00","level":"INFO","msg":"writer: Do: started","stream_id":"5jw37dgl"}
{"time":"2025-02-16T21:15:55.896751+02:00","level":"INFO","msg":"sender: started","stream_id":"5jw37dgl"}
{"time":"2025-02-16T21:15:55.896751+02:00","level":"INFO","msg":"handler: started","stream_id":"5jw37dgl"}
{"time":"2025-02-16T21:15:56.4628883+02:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-02-16T21:17:50.4326402+02:00","level":"WARN","msg":"sender: sendUseArtifact: job builder disabled, skipping"}
{"time":"2025-02-16T21:17:58.5219029+02:00","level":"WARN","msg":"sender: sendUseArtifact: job builder disabled, skipping"}
{"time":"2025-02-16T21:24:31.4053569+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.1.15:52859->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-16T21:24:33.3455886+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tmbuot-university-of-tripoli/llmapps/5jw37dgl/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-16T21:24:54.610978+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-16T21:24:56.6662431+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tmbuot-university-of-tripoli/llmapps/5jw37dgl/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-16T21:25:20.1195883+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-16T21:25:21.9469475+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tmbuot-university-of-tripoli/llmapps/5jw37dgl/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-16T21:25:50.0516683+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-16T21:25:52.4908646+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tmbuot-university-of-tripoli/llmapps/5jw37dgl/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-16T21:27:57.5628795+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/tmbuot-university-of-tripoli/llmapps/5jw37dgl/file_stream\": dial tcp 35.186.228.49:443: connectex: An established connection was aborted by the software in your host machine."}
