Loaded 374 JSON documents.
Token counts per document: [0, 0, 1445, 0, 2988, 5813, 320, 0, 7182, 4766, 0, 2094, 383, 321, 592, 2057, 2894, 0, 872, 743, 682, 717, 0, 249, 1852, 0, 589, 5603, 312, 0, 482, 1198, 437, 5035, 1010, 0, 0, 376, 433, 537, 496, 681, 0, 0, 751, 2103, 288, 322, 987, 1299, 555, 386, 0, 538, 494, 1771, 0, 537, 980, 401, 1338, 3058, 0, 725, 0, 769, 904, 1333, 1152, 0, 1389, 732, 0, 1936, 355, 542, 231, 1135, 1051, 960, 875, 0, 0, 582, 1987, 706, 524, 1135, 0, 0, 10123, 707, 2073, 0, 2694, 3148, 694, 685, 1238, 3291, 0, 589, 8763, 8490, 3392, 0, 6963, 3426, 0, 0, 753, 1161, 2540, 49, 11892, 2052, 293, 1931, 6114, 0, 185, 1387, 473, 3339, 921, 724, 490, 930, 1420, 961, 386, 0, 0, 334, 1053, 5406, 0, 825, 665, 2909, 242, 544, 1651, 2250, 0, 6343, 2470, 0, 664, 1760, 240, 855, 714, 1488, 566, 1689, 1856, 2179, 1583, 374, 534, 1304, 2327, 0, 0, 1632, 37, 697, 725, 1281, 3893, 662, 1355, 1111, 1479, 172, 458, 2050, 2998, 0, 555, 0, 2681, 1972, 312, 1242, 1221, 0, 508, 888, 994, 1768, 689, 736, 408, 742, 1685, 705, 2138, 0, 1199, 462, 527, 0, 1314, 641, 1326, 322, 0, 625, 3503, 1152, 0, 686, 1668, 2442, 707, 665, 0, 0, 173, 0, 1054, 2353, 652, 440, 464, 966, 0, 1107, 929, 0, 902, 1052, 933, 0, 2649, 1253, 1026, 1664, 629, 385, 0, 2355, 314, 418, 323, 573, 0, 2338, 1505, 949, 1480, 0, 211, 1117, 0, 0, 99, 0, 127, 1696, 4056, 0, 1976, 521, 561, 1330, 1717, 0, 0, 418, 1038, 918, 1085, 0, 864, 518, 663, 2432, 2078, 1955, 435, 210, 1153, 1556, 0, 0, 716, 1282, 1420, 1582, 1980, 364, 126, 688, 516, 0, 3116, 0, 557, 2876, 1079, 389, 0, 0, 6932, 677, 1744, 728, 0, 0, 1074, 4262, 2902, 818, 327, 1114, 0, 191, 0, 796, 2124, 926, 403, 1300, 176, 0, 0, 490, 0, 884, 1362, 2032, 2199, 2721, 2538, 1738, 0, 1440, 0, 1311, 305, 271, 3827, 1586, 4673, 136, 166, 396, 0, 257, 2601, 2034, 858, 0, 254, 998, 945, 606, 0, 514, 934, 439, 1642, 1861, 0, 744, 1041, 1628, 656, 563, 549, 1310]
Total document sections: 559
Example document section content:
أوَّلًا: أهميَّة الطَّهارةِ في الإسلامِ 1- عنايةُ الإسلامِ بالطَّهارةِ:قال اللهُ تبارك وتعالى لنبيِّه صلَّى اللهُ عليه وسلَّم في مستهلِّ دَعوتِه: وَثِيَابَكَ فَطَهِّرْ [المدثر: 4]  وقال صلَّى اللهُ عليه وسلَّم: ((الطُّهورُ شَطرُ الإيمانِ    قال ابن رجب: (الصحيحُ الذي عليه الأكثرون: أنَّ المرادَ بالطُّهورِ هاهنا: التَّطهُّرُ بالماء مِن الأحداثِ) ((جامع العلوم والحكم)) (2/7). )) رواه مسلم (223). من حديث أبي مالك الأشعريِّ رَضِيَ اللهُ عنه. 2- محبَّةُ اللهِ سبحانه للمُتطهِّرين:قال اللهُ تعالى: إِنَّ اللهَ يُحِبُّ التَّوَّابِينَ وَيُحِبُّ الْمُتَطَهِّرِينَ [البقرة: 222]  3- ثناؤه على المُتَطهِّرين:قال سبحانه: فِيهِ رِجَالٌ يُحِبُّونَ أَن يَتَطَهَّرُوا وَاللَّهُ يُحِبُّ الْمُطَّهِّرِينَ [التوبة: 108] ثانيًا: تعريفُ الطَّهارةِ وأقسامُهاتعريفُ الطَّهارةِالطَّهارة لُغةً: النَّزاهةُ والنَّظافةُ مِنَ الأدناسِ والأوساخِ ((لسان العرب)) لابن منظور (4/506)، ((أنيس الفقهاء)) للقونوي (1/5)، ((مواهب الجليل)) للحطَّاب (1/60)، ((الفروع)) لابن مفلح (1/56). الطَّهارةُ اصطلاحًا: رفْعُ الحدَثِ وما في معناه، وزوالُ الخَبَث ((مواهب الجليل)) للحطَّاب (1/60،61)، ((المجموع)) للنووي (1/79)، ((الشرح الممتع)) لابن عثيمين (1/26). فالطَّهارة تُطلَقُ على معنيينِ: أحدُهما: زَوالُ الخَبَثِ وهو النَّجاسةُ، والمقصودُ منه: طهارةُ البَدَنِ والثَّوبِ والمكانِ.والثَّاني: رفْعُ الحدَثِ (والمقصودُ منه: الطَّهارةُ بالوُضوءِ، والغُسلِ)، وما في معنى رفْعِ الحدَثِ، وهو كلُّ طهارةٍ لا يحصُلُ بها رفعُ الحَدَث، أو لا تكون عن حَدَثٍ ( كطهارةِ مَن به سَلَسُ بولٍ، أو تجديدِ الوضوءِ، وغَسلِ اليدينِ بعد القيامِ مِن نومِ اللَّيلِ). أقسامُ الطَّهارةأ- باعتبارِ مَحلِّها: وتنقسِمُ إلى قِسمينِ ((الشرح الممتع)) لابن عثيمين (1/25). :الأوَّلُ: الطَّهارةُ الباطِنةُ: وهي طهارةُ القَلبِ من الشِّرك، والغلِّ والبغضاءِ لعبادِ الله المؤمنينَ، وهي أهمُّ من طهارةِ البَدَنِ؛ بل لا يمكِنُ أن تقومَ طهارةُ البَدَنِ الشرعيَّةُ مع وجودِ نجَسِ الشِّركِ. - قال تعالى: إِنَّمَا الْمُشْرِكُونَ نَجَسٌ [التوبة: 28] - وعن أبي هريرة رَضِيَ اللهُ عنه أنَّ النبيَّ صلَّى اللهُ عليه وسلَّم قال: ((إنَّ المؤمِنَ لا يَنجُسُ    )) رواه البخاريُّ (285)، ومسلم (371).  الثَّاني: الطَّهارةُ الحسيَّة، وهي الطَّهارةُ مِنَ الأحداثِ والأنجاسِ.ب- باعتبارِ نَوعِها: النوع الأوَّل: الطَّهارةُ مِنَ الحدَثِوتنقسِمُ إلى ثلاثةِ أقسامٍ:الأوَّل: الطَّهارةُ الكبرى: وهي الغُسْلُ.الثَّاني: الطَّهارةُ الصُّغرى: وهي الوضوءُ.الثَّالث: طهارةٌ بدلٌ منهما: وهي التيمُّمُ.النَّوع الثَّاني: الطَّهارةُ مِنَ الخبَثِوتنقسِمُ إلى ثلاثةِ أقسامٍ:الأوَّل: طهارة غَسلٍ. الثَّاني: طهارة مَسحٍ.الثَّالث: طهارة نَضحٍ ((بداية المجتهد)) لابن رشد (1/7)، ((الفقه الإسلامي وأدلَّته)) للزحيلي
c:\dev\EE569\Assignment2-LLM\MYLLM\vectordatabase\vectordb.py:119: LangChainDeprecationWarning: The class `OpenAIEmbeddings` was deprecated in LangChain 0.0.9 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-openai package and should be used instead. To use it run `pip install -U :class:`~langchain-openai` and import as `from :class:`~langchain_openai import OpenAIEmbeddings``.
  embedding_function = OpenAIEmbeddings(openai_api_key=api_key)
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "C:\Python312\Lib\site-packages\httpx\_transports\default.py", line 250, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\httpcore\_sync\connection_pool.py", line 256, in handle_request
    raise exc from None
  File "C:\Python312\Lib\site-packages\httpcore\_sync\connection_pool.py", line 236, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\httpcore\_sync\connection.py", line 101, in handle_request
    raise exc
  File "C:\Python312\Lib\site-packages\httpcore\_sync\connection.py", line 78, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\httpcore\_sync\connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\httpcore\_backends\sync.py", line 207, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Python312\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(value)
  File "C:\Python312\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\openai\_base_client.py", line 996, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\httpx\_client.py", line 1014, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\httpx\_transports\default.py", line 249, in handle_request
    with map_httpcore_exceptions():
  File "C:\Python312\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(value)
  File "C:\Python312\Lib\site-packages\httpx\_transports\default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\dev\EE569\Assignment2-LLM\MYLLM\vectordatabase\vectordb.py", line 245, in <module>
    main()
  File "c:\dev\EE569\Assignment2-LLM\MYLLM\vectordatabase\vectordb.py", line 226, in main
    documents, vector_store = ingest_data(
                              ^^^^^^^^^^^^
  File "c:\dev\EE569\Assignment2-LLM\MYLLM\vectordatabase\vectordb.py", line 161, in ingest_data
    vector_store = create_vector_store(split_documents, vector_store_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\EE569\Assignment2-LLM\MYLLM\vectordatabase\vectordb.py", line 122, in create_vector_store
    vector_store = Chroma.from_documents(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\langchain_community\vectorstores\chroma.py", line 887, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\langchain_community\vectorstores\chroma.py", line 843, in from_texts
    chroma_collection.add_texts(
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\langchain_community\vectorstores\chroma.py", line 277, in add_texts
    embeddings = self._embedding_function.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\langchain_community\embeddings\openai.py", line 671, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\langchain_community\embeddings\openai.py", line 497, in _get_len_safe_embeddings
    response = embed_with_retry(
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\langchain_community\embeddings\openai.py", line 120, in embed_with_retry
    return embeddings.client.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\openai\resources\embeddings.py", line 124, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\openai\_base_client.py", line 1283, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\openai\_base_client.py", line 960, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\openai\_base_client.py", line 1020, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\openai\_base_client.py", line 1098, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\openai\_base_client.py", line 1020, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\openai\_base_client.py", line 1098, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\openai\_base_client.py", line 1030, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
[0m
