* Running on local URL:  http://Localhost:8844

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.
[34m[1mwandb[0m: Downloading large artifact vector_store:latest, 68.39MB. 6 files...
[34m[1mwandb[0m:   6 of 6 files downloaded.  
Done. 0:0:0.4
[34m[1mwandb[0m:   1 of 1 files downloaded.
Traceback (most recent call last):
<unknown>:1: SyntaxWarning: invalid escape sequence '\d'
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\gradio\queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\gradio\blocks.py", line 2042, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\gradio\blocks.py", line 1589, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\anyio\_backends\_asyncio.py", line 2461, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\anyio\_backends\_asyncio.py", line 962, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMB\AppData\Roaming\Python\Python312\site-packages\gradio\utils.py", line 883, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "c:\dev\EE569\Assignment2-LLM\LLM\app.py", line 78, in __call__
    self.chain = load_chain(
                 ^^^^^^^^^^^
  File "c:\dev\EE569\Assignment2-LLM\LLM\chain.py", line 56, in load_chain
    qa_prompt = load_chat_prompt(f"C:\dev\EE569\Assignment2-LLM\prompts.json")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\EE569\Assignment2-LLM\LLM\prompts.py", line 20, in load_chat_prompt
    template = json.load(f_name.open("r") ,encoding="utf-8")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'
